-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'LEARNER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CONTENT_EDITOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPPORT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'OWNER';
